//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migraw.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Migraw.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @php &quot;%~dp0composer.phar&quot; %*
        /// ähnelt.
        /// </summary>
        internal static string composer_bat {
            get {
                return ResourceManager.GetString("composer_bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die # Timeout: The number of seconds before receives and sends time out.
        ///Timeout 300
        ///
        ///# KeepAlive: Whether or not to allow persistent connections (more than
        ///# one request per connection). Set to &quot;Off&quot; to deactivate.
        ///KeepAlive On
        ///
        ///# MaxKeepAliveRequests: The maximum number of requests to allow
        ///# during a persistent connection. Set to 0 to allow an unlimited amount.
        ///MaxKeepAliveRequests 100
        ///
        ///# KeepAliveTimeout: Number of seconds to wait for the next request from the
        ///# same client on the same connectio [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string httpd {
            get {
                return ResourceManager.GetString("httpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [mysql]
        ///port                           = 3306
        ///
        ///[mysqld]
        ///skip-external-locking          = 1
        ///skip-grant-tables              = 1
        ///skip-name-resolve              = 1
        ///key-buffer-size                = 32M
        ///max-allowed-packet             = 16M
        ///max-connect-errors             = 1000000
        ///tmp-table-size                 = 32M
        ///max-heap-table-size            = 32M
        ///query-cache-type               = 0
        ///query-cache-size               = 0
        ///max-connections                = 512
        ///thread-cache-size              = 32
        ///ope [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string my {
            get {
                return ResourceManager.GetString("my", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;VirtualHost *:80&gt;
        ///	AcceptPathInfo On
        ///    UseCanonicalName Off
        ///    ServerAlias *
        ///    DocumentRoot &quot;[REPLACE]&quot;
        ///    &lt;Directory &quot;[REPLACE]&quot;&gt;
        ///		AllowOverride All
        ///		Options FollowSymLinks Indexes
        ///    &lt;/Directory&gt;
        ///&lt;/VirtualHost&gt; ähnelt.
        /// </summary>
        internal static string normal {
            get {
                return ResourceManager.GetString("normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @php &quot;%~dp0oxrun.phar&quot; %*
        /// ähnelt.
        /// </summary>
        internal static string oxrun_bat {
            get {
                return ResourceManager.GetString("oxrun_bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [PHP]
        ///
        ///;;;;;;;;;;;;;;;;;;;
        ///; About php.ini   ;
        ///;;;;;;;;;;;;;;;;;;;
        ///; PHP&apos;s initialization file, generally called php.ini, is responsible for
        ///; configuring many of the aspects of PHP&apos;s behavior.
        ///
        ///; PHP attempts to find and load this configuration from a number of locations.
        ///; The following is a summary of its search order:
        ///; 1. SAPI module specific location.
        ///; 2. The PHPRC environment variable. (As of PHP 5.2.0)
        ///; 3. A number of predefined registry keys on Windows (As of PHP 5.2.0)
        ///; 4. Current  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string php {
            get {
                return ResourceManager.GetString("php", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die php.exe -c &quot;%~dp0php.ini&quot; -d &quot;memory_limit=-1&quot; %*
        /// ähnelt.
        /// </summary>
        internal static string php_bat {
            get {
                return ResourceManager.GetString("php_bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #!/bin/bash
        ///# https://github.com/Microsoft/vscode/issues/22391
        ///# https://gist.github.com/aseering/a06219e74c7f96ccea5ec65d5b2483b5
        ///# Windowspath to Unix path echo &quot;$@&quot; | sed -e &apos;s|\\|/|g&apos; -e &apos;s|^\([A-Za-z]\)\:/\(.*\)|/mnt/\L\1\E/\2|&apos;
        ///CMD=$(echo $@ | sed -e &apos;s|/mnt/\([A-Za-z]\)/|\1:\\|&apos; -e &apos;s|/|\\|g&apos;)
        ///cmd.exe /c &quot;php.bat $CMD&quot;
        ///echo ähnelt.
        /// </summary>
        internal static string php_sh {
            get {
                return ResourceManager.GetString("php_sh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;VirtualHost *:80&gt;
        ///	AcceptPathInfo On
        ///    UseCanonicalName Off
        ///    ServerAlias *
        ///	VirtualDocumentRoot &quot;[REPLACE]&quot;
        ///    &lt;Directory *&gt;
        ///		AllowOverride All
        ///		Options FollowSymLinks Indexes
        ///    &lt;/Directory&gt;
        ///&lt;/VirtualHost&gt; ähnelt.
        /// </summary>
        internal static string wildcard {
            get {
                return ResourceManager.GetString("wildcard", resourceCulture);
            }
        }
    }
}
